apiVersion: v1
kind: PersistentVolume
metadata:
    name: volume01
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /home/diego/kind/volumes/volume01
    persistentVolumeReclaimPolicy: Retain
